worldEdit:
  maxBlockPerSecond: 5000
plottemplate: BauGsVorlage #If you want to update this, change the worldname! Else User cannot get a new plot
schempath: /root/test/schematics
tntReload:
  maxTnt: 1000
  materialType: TNT_MINECART
  timeout: 5                 #antispam
fernzuender: WOODEN_HOE
cannontimer:
  block:
    default: SHULKER_BOX
    active: LIME_SHULKER_BOX
    inactive: RED_SHULKER_BOX
  tool: CLOCK
  maxticks: 100

testworlds:
  template: BauGsVorlage
worldprice: 25000
maxworlds: 3
sizes:
  1:
    x: 23
    y: 23
    z: 23
    shields: 8
  2:
    x: 45
    y: 32
    z: 30
    shields: 12
  3:
    x: 67
    y: 41
    z: 37
    shields: 16
disallowedcommands:
  - '//' #all WE Commands
  - '/schem'
#  - /gs
#  - /arena
#  - /bau
#  - /hub
#  - /mw
#  - /schem list
#  - /schem load
#  - /schematic list
#  - /schematic load
#  - //schem list
#  - //schem load
#  - //schematic list
#  - //schematic load
#  - /luckperms
#  - /lpb
#  - /lp
#  - /msg
#  - /reply
#  - /r
#  -

  